name: 'Build Executables Workflow'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout and build'
        required: false
        type: string
        default: 'main'
      dotnet-version:
        description: '.NET version to use'
        required: false
        type: string
        default: '10.0.x'
    outputs:
      artifact-names:
        description: 'Names of uploaded artifacts'
        value: ${{ jobs.build_executables.outputs.artifact-names }}

jobs:
  build_executables:
    runs-on: macos-latest
    strategy:
      matrix:
        project: [Service, App, Tray, Cli]
    outputs:
      artifact-names: ${{ steps.set-names.outputs.names }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Build ${{ matrix.project }}
        uses: ./.github/actions/build-dotnet-project
        with:
          project: ${{ matrix.project }}
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Set artifact names
        id: set-names
        run: |
          names="${{ matrix.project }}-executables"
          echo "names=$names" >> $GITHUB_OUTPUT
